services:
#    my_app_cmsfony.example:
#        class: MyApp\CmsfonyBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }