my_app_cmsfony_front:
    resource: "@MyAppCmsfonyFrontBundle/Resources/config/routing.yml"
    prefix:   /

my_app_cmsfony:
    resource: "@MyAppCmsfonyBundle/Resources/config/routing.yml"
    prefix:   /
    


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
    